[[blogs]]
name = "Jixun"
url = "https://jixun.moe"
avatar = "https://secure.gravatar.com/avatar/8d55c3c3d7bb8d739444795a09d6ac9a?s=140&r=g"
description = "无所不知的 Jixun 姐姐"

[[blogs]]
name = "佳佳酱"
url = "https://luojia.me"
avatar = "https://secure.gravatar.com/avatar/f996917d71a03fa9d8e5393887620d7d?s=140&r=g"

[[blogs]]
name = "iKirby's Blog"
url = "https://ikirby.me"
avatar = "https://secure.gravatar.com/avatar/06d6ab60197ce094a60d051efb0685b1?s=140&r=g"

[[blogs]]
name = "偷揉"
url = "http://i.mouto.org"
avatar = "https://secure.gravatar.com/avatar/204c6600bea9f5d419e10b4b84b832de?s=140&r=g"
hidden = true

[[blogs]]
name = "MR158's Blog"
url = "https://mr158.cn/"
avatar = "https://secure.gravatar.com/avatar/91e432d6e35784b47fe7cc96fb85897d?s=140&r=g"

[[blogs]]
name = "蛋蛋的忧伤"
url = "https://www.ddnpc.com"
avatar = "https://secure.gravatar.com/avatar/c787859a634ea9f67a41ee2799577a16?s=140&r=g"

[[blogs]]
name = "橙的记事本"
url = "http://sell.moe"
avatar = "https://secure.gravatar.com/avatar/303504d3ba5b3c1502ec2c5bb3873b3d?s=140&r=g"

[[blogs]]
name = "OXの胡說八道"
url = "https://blog.ooxx.dk"
avatar = "https://secure.gravatar.com/avatar/6153bc164cce9c4bc56b11b8b71f70ba1858a75fc13f14a1111659ce6459261e?s=140&r=g"

[[blogs]]
name = "钉子の次元"
url = "https://blog.dimpurrc.com/"
avatar = "https://avatars.githubusercontent.com/u/5173244?s=140&r=g"
description = "An artist, designer and developer from China."

[[blogs]]
name = "qwe7002 的个人博客"
url = "https://www.qwe7002.com"
avatar = "https://secure.gravatar.com/avatar/829e35ddb6a7ea0f8f172284efab090f?s=140&r=g"

[[blogs]]
name = "C次元"
url = "https://ccoooss.com"
avatar = "https://avatars.githubusercontent.com/u/10512422?s=140&r=g"

[[blogs]]
name = "骤雨"
url = "https://hardrain980.com"
avatar = "https://secure.gravatar.com/avatar/79d886b1e6e5c452cbe92f9c244eaa3b47e562d641584fd1f1ea2e5bcafee781?s=140&r=g"

[[blogs]]
name = "Yay Ka-Boom-Boom"
url = "https://blog.nyan.im"
avatar = "https://gravatar.webp.se/avatar/7d19bd2fd8cfd8e4a8d8bb749784399a?s=140&r=g"

[[blogs]]
name = "Touko"
url = "https://touko.moe"
avatar = "https://entry.touko.moe/images/avatar.png"

[[blogs]]
name = "Cee"
url = "http://blog.cee.moe"
avatar = "https://avatars0.githubusercontent.com/u/5436953?v=3&s=140"

[[blogs]]
name = "Wis Chu"
url = "https://wischu.com"
avatar = "https://secure.gravatar.com/avatar/_?s=140&r=g"
hidden = true

[[blogs]]
name = "Clancey Lin"
url = "https://junebluez.com/"
avatar = "https://avatars.githubusercontent.com/u/8045582?s=140&r=g"
description = "翻涌在途，风景可艾。"

[[blogs]]
name = "Librazy"
url = "https://im.librazy.org"
avatar = "https://avatars.githubusercontent.com/u/2211542?s=140&r=g"
description = "Liqueur Librazy 的 Dream Library"

[[blogs]]
name = "zsx"
url = "https://www.zsxsoft.com"
avatar = "https://avatars.githubusercontent.com/u/2398785?s=140&r=g"

[[blogs]]
name = "kookxiang"
url = "https://ikk.me"
avatar = "https://secure.gravatar.com/avatar/_?s=140&r=g"
hidden = true

[[blogs]]
name = "灰灰 の blog"
url = "https://huihui.moe"
avatar = "https://avatars.githubusercontent.com/u/1707683?s=140&r=g"
description = "妹妹才是真爱！贫乳才是正义！٩(๑òωó๑)۶"

[[blogs]]
name = "贫困的蚊子"
url = "https://qwq.moe"
avatar = "https://avatars.githubusercontent.com/u/11910831?v=4&s=140"
description = "幸福往往是摸得透彻，而堇业的心却常常隐藏"

[[blogs]]
name = "Mokeyjay's Blog - 超能小紫"
url = "https://mok.moe/"
avatar = "https://secure.gravatar.com/avatar/002733a5a1c5c0d409aa4fa1f414bfe1?s=140&r=g"
description = "资深全沾工程师"

[[blogs]]
name = "天空・边界"
url = "https://liyin.date"
avatar = "https://avatars.githubusercontent.com/u/8038511?s=140&r=g"
description = "相传胜利者肯定手持正义 那仅是因为正义可以被胜利者定义"

[[blogs]]
name = "Chaos"
url = "https://chaos.run"
avatar = "https://secure.gravatar.com/avatar/468aaff1651e7f166b43581f07a57528?s=140&r=g"
description = "I seek truth"

[[blogs]]
name = "三言三语"
url = "https://best33.com"
avatar = "https://secure.gravatar.com/avatar/41b9137148b6e21ed2216fcfd12abfcf?s=140&r=g"

[[blogs]]
name = "LWL 的自由天空"
url = "https://blog.lwl12.com"
avatar = "https://secure.gravatar.com/avatar/_?s=140&r=g"
hidden = true

[[blogs]]
name = "流转着绮丽光芒的秘境"
url = "https://blog.gogo.moe"
avatar = "https://secure.gravatar.com/avatar/e9516b38df0e414fe8b91a2aa890b4d8?s=140&r=g"

[[blogs]]
name = "251 的魔法实验室"
url = "https://blog.251.sh"
avatar = "https://avatars.githubusercontent.com/u/3908746?s=140&r=g"
description = "您要的页面找不到了，但我们不能停止斗争。"

[[blogs]]
name = "lolly"
url = "https://lolly.cc"
avatar = "https://secure.gravatar.com/avatar/_?s=140&r=g"
hidden = true

[[blogs]]
name = "Jimmy Tian's Blog"
url = "https://twznow.com"
avatar = "https://secure.gravatar.com/avatar/0b7a4c2253965e346881bf944d17781f?s=140&r=g"

[[blogs]]
name = "哞菇 / Nekotora"
url = "http://flag.moe"
avatar = "https://avatars.githubusercontent.com/u/7263028?s=140&r=g"

[[blogs]]
name = "StarryVoid"
url = "https://www.starryvoid.com"
avatar = "https://avatars.githubusercontent.com/u/20756365?s=140&r=g"

[[blogs]]
name = "Yuuno Blog"
url = "https://yuuno.cc"
avatar = "https://secure.gravatar.com/avatar/_?s=140&r=g"
hidden = true

[[blogs]]
name = "Makito's Notebook"
url = "https://blog.keep.moe"
avatar = "https://avatars.githubusercontent.com/u/5277268?s=140&r=g"

[[blogs]]
name = "米米的博客"
url = "https://zhangshuqiao.org"
avatar = "https://secure.gravatar.com/avatar/f56980e9dc026727282a04eea02b4f4d?s=140&r=g"
description = "做了一点微小的工作"

[[blogs]]
name = "映雪青帖"
url = "https://www.aoisnow.net"
avatar = "https://secure.gravatar.com/avatar/undefined?s=140&r=g"

[[blogs]]
name = "时间回廊"
url = "https://xbtzone.com/blog/"
avatar = "https://avatars.githubusercontent.com/u/14367819?s=140&r=g"

[[blogs]]
name = "白熊阿丸的小屋"
url = "https://bxaw.name"
avatar = "https://secure.gravatar.com/avatar/21531185e8296f70da566b68d3fc9785?s=140&r=g"
description = "在这里可以看到一个真实的我，我会在这里书写我的一切"

[[blogs]]
name = "Ceplavia's Gaming Blog"
url = "https://www.ceplavia.com/"
avatar = "https://avatars.githubusercontent.com/u/8531743?s=140&r=g"

[[blogs]]
name = "硅碳双键的文艺复兴"
url = "https://iluvrachel.github.io/"
avatar = "https://secure.gravatar.com/avatar/_?s=140&r=g"
hidden = true

[[blogs]]
name = "保罗的小宇宙"
url = "https://paugram.com/"
avatar = "https://secure.gravatar.com/avatar/d22eb460ecab37fcd7205e6a3c55c228?s=140&r=g"
description = "Still single, still waiting..."

[[blogs]]
name = "派兹的小站"
url = "https://blog.blw.moe/"
avatar = "https://secure.gravatar.com/avatar/da55a11e39638a60a814d76666be5782?s=140&r=g"
description = "驶向天空之船"

[[blogs]]
name = "Bottle's Blog"
url = "https://bottle.moe/"
avatar = "https://secure.gravatar.com/avatar/c3849bc3831321334ea3f871e675448b?s=140&r=g"

[[blogs]]
name = "神楽坂 の 猫"
url = "https://kagurazaka.cat/"
avatar = "https://secure.gravatar.com/avatar/_?s=140&r=g"
hidden = true

[[blogs]]
name = "DWCarrot's 小站"
url = "https://dwcarrot.github.io/blog/"
avatar = "https://avatars.githubusercontent.com/u/23579844?v=4&s=140&r=g"
description = "DWCarrot's personal home page & blog"

[[blogs]]
name = "Citing's Blog"
url = "https://citingnutria.github.io/"
avatar = "https://secure.gravatar.com/avatar/738e1e6d6412c0be95ca62934cb51382?s=140&r=g"
description = "まだ夢がある"

[[blogs]]
name = "苏卡卡的有底洞"
url = "https://blog.skk.moe/"
avatar = "https://cdn.skk.moe/avatar/144x144.png"
description = "童话只美在真实却从不续写"

[[blogs]]
name = "Herry 的平行世界"
url = "https://blog.herry001.com/"
avatar = "https://secure.gravatar.com/avatar/fa343197e57e59887e02ab7392f0dac6?s=140&r=g"
description = "平行世界 ##1"

[[blogs]]
name = "CronfoxBlog"
url = "https://cronfox.2434.me/"
avatar = "https://secure.gravatar.com/avatar/6d330f7f6285758d1fe88467fdf56835?s=140&r=g"
description = "何がここまであなたをうごかすの？"

[[blogs]]
name = "秋实-Allenyou 的小窝"
url = "https://www.allenyou.wang/"
avatar = "https://secure.gravatar.com/avatar/59b2fbdd507a84fe181b0af3e4ad7be3?s=140&r=g"
description = "稻花香里说丰年，听取WA声一片"

[[blogs]]
name = "boNote"
url = "https://note.bobo.moe/"
avatar = "https://secure.gravatar.com/avatar/150bf1b639e1da739c373427e6668ba8?s=140&r=g"

[[blogs]]
name = "海上的宫殿"
url = "https://soha.moe/"
avatar = "https://secure.gravatar.com/avatar/5bf3f242d4fdca6849d31792a3c83c80?s=140&r=g"
description = "是你想来Soha的在海上宫殿参观吗？"

[[blogs]]
name = "Kirin's Backspace"
url = "https://9baka.moe/"
avatar = "https://secure.gravatar.com/avatar/24bf9fa4459198c2dd2c482439d46b24?s=140&r=g"
description = "六月始めに生まれ、八月終わりに遠のいた"

[[blogs]]
name = "新世界的大门"
url = "https://blog.xinshijiededa.men"
avatar = "https://avatars.githubusercontent.com/u/20166026?v=4&s=140"
description = "因此幻想是世界，谁若懂得，谁就会歌唱"

[[blogs]]
name = "LineXic书屋"
url = "https://linexic.top"
avatar = "https://gravatar.com/avatar/ad6c462d000be54889b98f669fd56a64?s=140&r=g"
description = "难离难舍，想抱紧些"

[[blogs]]
name = "liruifengv"
url = "https://liruifengv.com"
avatar = "https://avatars.githubusercontent.com/u/25167721?v=4&s=140"
description = "Web 开发者，Astro 项目成员，开源爱好者。"

[[blogs]]
name = "Pink Champagne"
url = "https://pcp.moe"
avatar = "https://avatars.githubusercontent.com/PinkChampagne17?v=4&s=140"
description = "长发大哥哥！"

[[blogs]]
name = "Amamiya Miu"
url = "https://miuchan.github.io/"
avatar = "https://avatars.githubusercontent.com/u/4667188?v=4&s=140"
description = "Earth Online・体验实验室"

[[blogs]]
name = "NknSのSitE"
url = "https://nkns.cc"
avatar = "https://secure.gravatar.com/avatar/1cbb0269e34002e6943b5f6c64e2312bc751024f92d10fad7ea0b755780bb30c?s=140&r=g"
description = "Ich liebe dich."

[[blogs]]
name = "cosine = 余弦の博客"
url = "https://blog.cosine.ren"
avatar = "https://avatars.githubusercontent.com/u/43498495?v=4&s=140"
description = "博客主题超可爱的大姐姐www"

[[blogs]]
name = "Hakadao"
url = "https://hakadao.cc"
avatar = "https://avatars.githubusercontent.com/u/33394391?v=4&s=140"
description = "Now I am become a loser, the destroyer of myself."

[[blogs]]
name = "Hikaru Lab"
url = "https://www.mengxiblog.top"
avatar = "https://avatars.githubusercontent.com/u/106070298?v=4&s=140"
description = "即使是人造的记忆，也有它存在的价值"

[[blogs]]
name = "薄荷の小屋"
url = "https://www.hoshiroko.com"
avatar = "https://secure.gravatar.com/avatar/c5ed321913c6237263cd33e49329048939aea14cc7b8ab40fcca914ea54f1690?s=140&r=g"
description = "越是拼命往前伸手，渴望之物越是渐行渐远"

[[blogs]]
name = "槑囿脑袋"
url = "https://chentao0717.cn/"
avatar = "https://avatars.githubusercontent.com/u/70054568?v=4&s=140"
description = "Keep Coding, Keep Learning."

[[nonBlogs]]
name = "三千院の暗"
url = "http://moe.lu"
avatar = "https://q2.qlogo.cn/headimg_dl?dst_uin=133834400&spec=140"

[[nonBlogs]]
name = "Mashiro Usagi"
url = "http://daisuke.moe/"
avatar = "https://secure.gravatar.com/avatar/21af46cb6baae2b402c332b949c82ed6?s=140&r=g"
